# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteT', '0005_posta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posta',
            name='author',
        ),
        migrations.DeleteModel(
            name='Posta',
        ),
    ]
