# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteT', '0008_auto_20160126_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('CPF', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=20)),
                ('email_user', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=5)),
            ],
        ),
    ]
